windowrulev = noblur, class:.*

# Window rules
windowrulev = float, class:^(steam)$
windowrulev = float, class:^(wechat)$
windowrulev = float, class:^(QQ)$

# Dialogs
windowrulev = center, title:^(Open File)(.*)$
windowrulev = center, title:^(Select a File)(.*)$
windowrulev = center, title:^(Choose wallpaper)(.*)$
windowrulev = center, title:^(Open Folder)(.*)$
windowrulev = center, title:^(Save As)(.*)$
windowrulev = center, title:^(Library)(.*)$
windowrulev = center, title:^(File Upload)(.*)$
windowrulev = float, title:^(Open File)(.*)$
windowrulev = float, title:^(Select a File)(.*)$
windowrulev = float, title:^(Choose wallpaper)(.*)$
windowrulev = float, title:^(Open Folder)(.*)$
windowrulev = float, title:^(Save As)(.*)$
windowrulev = float, title:^(Library)(.*)$
windowrulev = float, title:^(File Upload)(.*)$
windowrulev = float,  title:^(微信)(.*)$
