include mocha.conf

background_opacity 0.97

font_family      SauceCodePro Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14.0

cursor_shape          beam
cursor_blink_interval 0

copy_on_select yes

map --new-mode mw --on-action end ctrl+s

map --mode mw h neighboring_window left
map --mode mw l neighboring_window right
map --mode mw k neighboring_window up
map --mode mw j neighboring_window down

map --mode mw enter launch --location=first
map --mode mw x close_window
map --mode mw q focus_visible_window

map --mode mw , set_tab_title

map --mode mw c new_tab

map --mode mw 1 goto_tab 1
map --mode mw 2 goto_tab 2
map --mode mw 3 goto_tab 3
map --mode mw 4 goto_tab 4

inactive_text_alpha 0.3
window_border_width 1pt

tab_bar_min_tabs            1
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
