[[env]]
name = "MODULE_DOMAIN"
from_repo = "clone"
value = "test"

[[env]]
name = "MODULE_OWNER"
from_repo = "owner"
value = "test"

[[env]]
name = "MODULE_NAME"
from_repo = "name"

[[steps]]
name = "main.go"
file = """
package main

import "fmt"

func main() {
\tfmt.Println("hello, world!")
}
"""

[[steps]]
name = "Go module"
run = "go mod init ${MODULE_DOMAIN}/${MODULE_OWNER}/${MODULE_NAME}"
